config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"

  get "/menus/changemenu" => "menus#changeMenu", as: :change_menus
  put "/menus/:id/updateMenuName" => "menus#updateMenuName"
  put "menu_items/:id/updateMenuItem" => "menu_items#updateMenuItem"

  get "/signin/new" => "sessions#new", as: :new_session
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy"

  get "/reports/:id" => "reports#invoice", as: :invoice

  post "/orderdeliver/:id" => "orders#deliverOrder"
  post "/orders/confirm" => "orders#confirm"
  get "/orders/cart" => "orders#cart", as: :carts

  put "/order_items/:id/decrement" => "order_items#decrement"
  put "/order_items/:id/decrementInCart" => "order_items#decrementInCart"

  post "/order_items/:id/addToCart" => "order_items#addToCart"

  put "/order_items/:id/increment" => "order_items#increment"
  put "/order_items/:id/incrementInCart" => "order_items#incrementInCart"

  get "/CafeAddressShow" => "others#cafeAddressShow"
  post "/CafeAddressUpdate" => "others#cafeAddressUpdate"

  resources :menus
  resources :menu_items
  resources :order_items
  resources :users
  resources :categories
  resources :reports
  resources :orders
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :menu_items, dependent: :delete_all
  validates :name, presence: true

  def isActive?
    active
  end

  def itemsByCategory
    itemsByCategory = {}
    categories = Category.order(:id).all
    categories.map do |category|
      current_category_menu_items = menu_items.order(:id).where(category_id: category.id)
      if current_category_menu_items.count > 0
        itemsByCategory[category.id] = current_category_menu_items
      end
    end
    return itemsByCategory
  end

  def menuItemsCheckedCount
    menu_items.where(active: true).count
  end

  def self.activeMenusCount
    Menu.where(active: true).count
  end

  def self.displayable
    menus = Menu.order(:id).map { |menu| [menu.name, menu.id] }
    menus.unshift(["Select Menu", ""])
    return menus
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :ensure_user_logged_in, only: [:index]
  before_action :ensure_owner_logged_in, only: [:show, :changeMenu]

  def index
    if session[:current_order_id] == nil
      orders = Order.where(user_id: current_user.id)
      if orders
        previous_order = orders.find_by(status: "notprocessed")
        if previous_order
          session[:current_order_id] = previous_order.id
        end
      end
      if session[:current_order_id] == nil
        user_id = current_user.id
        order = Order.create!(user_id: user_id, date: DateTime.now, delivered_at: nil, status: "notprocessed", price: 0)
        session[:current_order_id] = order.id
      end
    end
    displayableCategoryItems = Category.displayableCategoryItems
    render "index", locals: { displayableCategoryItems: displayableCategoryItems }
  end

  def create
    name = params[:name]
    menu = Menu.new(name: name, active: false)
    if menu.valid?
      menu.save
    else
      flash[:error] = menu.errors.full_messages.join(", ")
    end
    redirect_to change_menus_path
  end

  def show
    id = params[:id]
    session[:current_selected_menu_id] = id
    menu = Menu.find(id)
    categories = Category.displayable
    render "display_menu", locals: { menu: menu, categories: categories }
  end

  def edit
    id = params[:id]
    menu = Menu.find(id)
    render "menu_edit", locals: { menu: menu }
  end

  def update
    id = params[:id]
    if params[:active]
      active = true
    else
      active = false
    end
    menu = Menu.find(id)
    menu.active = active
    menu.save
    if !active
      Order.deleteCurrentMenuCartItems(menu)
    end
    redirect_to change_menus_path
  end

  def updateMenuName
    id = params[:id]
    menu = Menu.find(id)
    menu.name = params[:name]
    if menu.valid?
      menu.save
      flash[:notice] = "Update Successful"
      redirect_to change_menus_path
    else
      flash[:error] = menu.errors.full_messages.join(", ")
      redirect_to edit_menu_path
    end
  end

  def destroy
    id = params[:id]
    menu = Menu.find(id)
    Order.deleteCurrentMenuCartItems(menu)
    menu.destroy
    redirect_to change_menus_path
  end

  def changeMenu
    render "activeMenus"
  end
end

app/views/menus/_display_menu_items.html.erb
<% menu.itemsByCategory.each do |category_id,menu_items| %>
  <% category = Category.find(category_id) %>
  <div class="menu-categories">
    <h1 class="menu-category-name"> <%=category.name%> </h1>
    <p class = "menu-category-item-count"> <%= category.menuItemsCheckedCount(menu.id) %> / <%= category.allMenuItemsCount(menu.id) %> </p>
    <ul class="menu-category-menu-items">
      <% menu_items.each do |menu_item| %>
        <li class="menu-category-menu-item">
          <%= form_with(url: "/menu_items/#{menu_item.id}", method: "put") do %>
            <% checked = menu_item.active %>
            <%= check_box_tag(:active, nil, checked, class: "menu-category-menu-item-checkbox", onclick: "this.form.submit()") %>
          <% end %>
          <p class="menu-category-menu-item-name" > <%=menu_item.name%> </p>
          <p class="menu-category-menu-item-description" > <%=menu_item.description%> </p>
          <p class="menu-category-menu-item-price" > <i class="fa fa-inr" aria-hidden="true"></i> <%=menu_item.price%> </p>
          <div class="edit-delete-block">
            <%= form_with(url: "/menu_items/#{menu_item.id}", method: "delete") do %>
              <%= image_submit_tag("TrashIcon.png", class: "menu-category-menu-item-delete") %>
            <% end %>
            <p class="menu-category-menu-item-edit-icon"> <%= link_to ('<i class="fa fa-pencil"></i>').html_safe, "/menu_items/#{menu_item.id}/edit" %> </p>
          </div>
        </li>
      <% end %>
    </ul>
    <hr>
  </div>
<% end %>

app/views/menus/activeMenus.html.erb
<section class="container">
  <%= form_with(url: menus_path, method: "post", class: "new") do %>
    <%= text_field_tag(:name, nil, class: "form-input", placeholder: "Enter the new menu name", autofocus: "autofocus") %>
    <%= submit_tag("Create!", class: "margin-left-20 form-submit", data: {disable_with: "Creating.."}) %>
  <% end %>
  <div class="active-count">
    <h1 class="active-menus-count"> <%= Menu.activeMenusCount %> / <%= Menu.all.count %> Active menus </h1>
    <h1 class="active-items-count"> <%= MenuItem.activeMenuItemsCount %> / <%= MenuItem.all.count %> Active menu items </h1>
  </div>
  <div class="menus">
    <% Menu.order(:id).all.each do |menu| %>
      <div class = "menu">
        <%= form_with(url: "/menus/#{menu.id}", method: "put") do %>
          <% checked = menu.active %>
          <%= check_box_tag(:active, nil, checked, class: "menu-checkbox", onclick: "this.form.submit()") %>
        <% end %>
        <%= link_to "#{menu.name}", "/menus/#{menu.id}", class: "menu-name menu-underlineHover" %>
        <p class="menu-items-count"> <%= menu.menuItemsCheckedCount %>/<%= menu.menu_items.count %> items </p>
        <div class="edit-delete-block">
          <%= form_with(url: "/menus/#{menu.id}", method: "delete") do %>
            <%= image_submit_tag("TrashIcon.png", class: "activeMenus-trash-icon") %>
          <% end %>
          <p class="activeMenus-edit-icon"> <%= link_to ('<i class="fa fa-pencil"></i>').html_safe, "/menus/#{menu.id}/edit" %> </p>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/menus/display_menu.html.erb
<%= link_to change_menus_path do %>
  <p class="back-button"> <i class="fa fa-arrow-circle-left" aria-hidden="true"></i> All Menus </h1>
<% end %>
<section class="add-menu-item">
  <%= form_with(url: menu_items_path, method: "post", class: "add-menu-item-left") do %>
    <%= text_field_tag(:name, nil, class: "form-input", placeholder: "Enter the new item name", autofocus: "autofocus") %>
    <%= text_area_tag(:description, nil, size: "25x4", class: "add-menu-item-text-area", placeholder: "Item description") %>
    <%= select_tag nil, options_for_select(categories), class: "category-dropdown", name: "category_id" %>
    <%= number_field(nil, nil, class: "form-input", placeholder: "Enter Price", name: "price", min: 1) %>
    <%= submit_tag("Add Item!", class: "form-submit", data: {disable_with: "Adding.."}) %>
  <% end %>
  <section class="add-menu-item-right">
    <h1 class = "menu-content-menu-name"> <%= menu.name %> </h1>
    <p class = "menu-content-item-count"> <%= menu.menuItemsCheckedCount %> / <%= menu.menu_items.count %> </p>
    <%= render partial: "display_menu_items", locals: { menu: menu } %>
  </section>
</section>

app/views/menus/index.html.erb
<%= link_to "/orders/cart" do %>
  <p class="go-to-cart"> <i class="fa fa-shopping-cart cart-icon" aria-hidden="true"></i> Go to Cart </p>
<% end %>

<div class="container">
  <% displayableCategoryItems.each do |category_name,menu_items| %>
    <div class="categories">
      <h1 class="category-name"> <%=category_name%> </h1>
      <ul class="category-items">
        <% menu_items.each do |menu_item| %>
          <li class="category-item">
            <p class="menu-item-name"> <%=menu_item.name%> </p>
            <p class="menu-item-description"> <%=menu_item.description%> </p>
            <p class="menu-item-price"> <i class="fa fa-inr" aria-hidden="true"></i> <%=menu_item.price%> </p>
            <% order_item = Order.find(session[:current_order_id]).order_items.find_by(menu_item_id: menu_item.id) %>
            <div class="menu-item-quantity">
              <% if order_item %>
                <%= form_with(url: "/order_items/#{menu_item.id}/decrement", method: "put") do%>
                  <%= submit_tag("-", class: "decrement-button")%>
                <% end %>
                <p class="menu_item-quantity"><%= order_item.quantity%></p>
                <%= form_with(url: "/order_items/#{menu_item.id}/increment", method: "put") do%>
                  <%= submit_tag("+", class: "increment-button")%>
                <% end %>
              <% else %>
                <%= form_with(url: "/order_items/#{menu_item.id}/addToCart", method: "post") do%>
                  <%= submit_tag("Add", class: "add-button")%>
                <% end %>
              <% end %>
            <div>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/menus/menu_edit.html.erb
<%= form_with(url: "/menus/#{menu.id}/updateMenuName", method: "put", class: "update-menu-form") do %>
  <%= text_field_tag(:name, nil, class: "form-input", value: menu.name, placeholder: "Enter new menu name", autofocus: "autofocus") %>
  <%= submit_tag("Update!", class: "form-submit", data: {disable_with: "Updating.."}) %>
<% end %>