config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"

  get "/menus/changemenu" => "menus#changeMenu", as: :change_menus
  put "/menus/:id/updateMenuName" => "menus#updateMenuName"
  put "menu_items/:id/updateMenuItem" => "menu_items#updateMenuItem"

  get "/signin/new" => "sessions#new", as: :new_session
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy"

  get "/reports/:id" => "reports#invoice", as: :invoice

  post "/orderdeliver/:id" => "orders#deliverOrder"
  post "/orders/confirm" => "orders#confirm"
  get "/orders/cart" => "orders#cart", as: :carts

  put "/order_items/:id/decrement" => "order_items#decrement"
  put "/order_items/:id/decrementInCart" => "order_items#decrementInCart"

  post "/order_items/:id/addToCart" => "order_items#addToCart"

  put "/order_items/:id/increment" => "order_items#increment"
  put "/order_items/:id/incrementInCart" => "order_items#incrementInCart"

  get "/CafeAddressShow" => "others#cafeAddressShow"
  post "/CafeAddressUpdate" => "others#cafeAddressUpdate"

  resources :menus
  resources :menu_items
  resources :order_items
  resources :users
  resources :categories
  resources :reports
  resources :orders
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if @current_user
      redirect_to menus_path
    else
      # @signUpFlag = false
      # render "index"
      redirect_to new_session_path
    end
  end
end

app/views/home/_signin-signup.html.erb
<!-- Tabs Titles -->
<div class="tab-titles">
<% if signUpFlag %>
<%   signin = "sign-in underlineHover" %>
<%   signup = "sign-up active" %>
<% else %>
<%   signup = "sign-up underlineHover" %>
<%   signin = "sign-in active" %>
<% end %>
<%= link_to "Sign In", new_session_path, class: signin %>
<%= link_to "Sign Up", new_user_path, class: signup %>
</div>

<% if signUpFlag %>
  <%= form_with(url: users_path, method: "post", class: "home-form-inputs") do %>
    <%= text_field_tag(:name, nil, class: "home-form-input", placeholder: "name") %>
    <%= email_field(nil, nil, name: "email", class: "home-form-input", placeholder: "E-mail") %>
    <%= password_field(nil, nil, name: "password", class: "home-form-input", placeholder: "password")%>
    <%= telephone_field(nil, nil, name: "phone", class: "home-form-input", placeholder: "contact number") %>
    <%= text_area_tag(:address, nil, size: "35x6", placeholder: "address", class: "home-form-input") %>
    <%= submit_tag("Sign Up!", class: "home-form-input log-in", data: {disable_with: "Signing Up.."}) %>
  <% end %>
<% else %>
  <%= form_with(url: sessions_path, method: "post", class: "home-form-inputs") do %>
    <%= text_field_tag(:email, nil, class: "home-form-input", placeholder: "email") %>
    <%= password_field(nil, nil, name: "password", class: "home-form-input", placeholder: "password")%>
    <%= submit_tag("Sign In!", class: "home-form-input log-in", data: {disable_with: "Signing In.."}) %>
  <% end %>
<% end %>

app/views/home/index.html.erb
<div class="signin-signup-block">
  <div class="form-content">
    <%= render partial: "home/signin-signup", locals: { signUpFlag: @signUpFlag } %>
  </div>
</div>