config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"

  get "/menus/changemenu" => "menus#changeMenu", as: :change_menus
  put "/menus/:id/updateMenuName" => "menus#updateMenuName"
  put "menu_items/:id/updateMenuItem" => "menu_items#updateMenuItem"

  get "/signin/new" => "sessions#new", as: :new_session
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy"

  get "/reports/:id" => "reports#invoice", as: :invoice

  post "/orderdeliver/:id" => "orders#deliverOrder"
  post "/orders/confirm" => "orders#confirm"
  get "/orders/cart" => "orders#cart", as: :carts

  put "/order_items/:id/decrement" => "order_items#decrement"
  put "/order_items/:id/decrementInCart" => "order_items#decrementInCart"

  post "/order_items/:id/addToCart" => "order_items#addToCart"

  put "/order_items/:id/increment" => "order_items#increment"
  put "/order_items/:id/incrementInCart" => "order_items#incrementInCart"

  get "/CafeAddressShow" => "others#cafeAddressShow"
  post "/CafeAddressUpdate" => "others#cafeAddressUpdate"

  resources :menus
  resources :menu_items
  resources :order_items
  resources :users
  resources :categories
  resources :reports
  resources :orders
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Night life</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Google fonts %>
    <%# Nav bar %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Cedarville+Cursive|Sacramento&display=swap' %>
    <%# Welcome block %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap' %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main-content">
      <header id="main-header">
	  	  <div class="container navbar">
          <div class="left-part">
            <%= link_to "/" do %>
              <h1 class="navbar-title"> <i class="fa fa-cutlery brand-icon" aria-hidden="true"></i>Restro</h1>
            <% end %>
          </div>
          <div class="right-part">
            <p class="quote">Night is young & So we are!!</p>
	  		    <div class="tags">
              <%= link_to "/" do %>
                <p class="tag"> <i class="fa fa-home"></i> Home </p>
              <% end %>
              <% if @current_user %>
                <%= link_to carts_path do %>
                  <p class="tag"> <i class="fa fa-shopping-cart tag-fa" aria-hidden="true"></i> Cart </p>
                <% end %>
                <%= link_to orders_path do %>
                  <p class="tag"> <i class="fa fa-files-o tag-fa" aria-hidden="true"></i> Orders </p>
                <% end %>
                <div class="drop-down-tags-menu">
                  <i class="fa fa-chevron-down drop-down-arrow tag" aria-hidden="true"></i>
                  <div class="drop-down-tags">
                    <%= link_to "/users/#{@current_user.id}" do %>
                      <p class="drop-down-tag"> <i class="fa fa-id-card tag-fa" aria-hidden="true"></i> Profile </p>
                    <% end %>
                    <% if @current_user.role == "owner" %>

                      <%= link_to change_menus_path do %>
                        <p class="drop-down-tag"> <i class="fa fa-files-o tag-fa" aria-hidden="true"></i> Change Menu </p>
                      <% end %>
                      <%= link_to categories_path do %>
                        <p class="drop-down-tag"> <i class="fa fa-list tag-fa" aria-hidden="true"></i> Categories </p>
                      <% end %>
                      <%= link_to reports_path do %>
                        <p class="drop-down-tag"> <i class="fa fa-clone tag-fa" aria-hidden="true"></i> Reports </p>
                      <% end %>
                    <% end %>
                    <% if @current_user.role != "customer" %>


                    <% end %>
                    <%= link_to "/signout",method: "delete" do %>
                      <p class="drop-down-tag"> <i class="fa fa-sign-out tag-fa" aria-hidden="true"></i> SignOut </p>
                    <% end %>
                  </div>
                </div>
              <% else %>

                <% if @signUpFlag %>
                  <%= link_to new_session_path do %>
                    <p class="tag"> <i class="fa fa-sign-in tag-fa" aria-hidden="true"></i> SignIn </p>
                  <% end %>
                <% else %>
                  <%= link_to new_user_path do %>
                    <p class="tag"> <i class="fa fa-user-plus tag-fa" aria-hidden="true"></i> SignUp </p>
                  <% end %>
                <% end %>
              <% end %>
	  		    </div>
          </div>
	  	  </div>
	    </header>

      <% if flash[:error] %>
        <p class = "flash flash-error">
          <i class="fa fa-exclamation-triangle" aria-hidden="true"></i> <%= flash[:error] %>
        </p>
      <% end %>
      <% if flash[:notice] %>
        <p class = "flash flash-notice">
          <i class="fa fa-check" aria-hidden="true"></i> <%= flash[:notice] %>
        </p>
      <% end %>

      <%= yield %>

    </div>

  </body>
</html>